propel:
  copypasta:
    id:
    copypasta_language_id:
    copypasta:              longvarchar
    username:               varchar(50)
    delete_at:              timestamp
    created_at:

  copypasta_language:
    id:
    title: varchar(50)
    position: integer
