# default rules
homepage:
  url:   /
  param: { module: index, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
